# Generated by Django 6.0.2 on 2026-02-13 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_create_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fetcher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "fetcher_type",
                    models.CharField(
                        choices=[
                            ("seedlist", "Seedlist"),
                            ("monitor", "Monitor"),
                            ("full_site", "Full Site"),
                            ("discovery", "Discovery"),
                            ("rss", "Rss"),
                            ("sitemap", "Sitemap"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paused", "Paused"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("use_headless", models.BooleanField(default=False)),
                ("use_rotating_proxy", models.BooleanField(default=False)),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("once", "Once"),
                            ("interval", "Interval"),
                            ("cron", "Cron"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "cron_schedule_config",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("depth", models.IntegerField(default=3)),
                ("inclusion_domains", models.JSONField(default=list)),
                ("exclusion_domains", models.JSONField(default=list)),
                (
                    "output_format",
                    models.CharField(
                        choices=[("warc", "Warc"), ("gzip", "Gzip")], max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.collection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FetcherRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pages_crawled", models.IntegerField(default=0)),
                ("bytes_downloaded", models.IntegerField(default=0)),
                ("total_requests", models.IntegerField(default=0)),
                ("total_errors", models.IntegerField(default=0)),
                ("total_timeouts", models.IntegerField(default=0)),
                ("total_redirects", models.IntegerField(default=0)),
                ("total_failures", models.IntegerField(default=0)),
                ("total_successes", models.IntegerField(default=0)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fetcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.fetcher"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FetcherSeedlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fetcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.fetcher"
                    ),
                ),
            ],
        ),
    ]
